//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_CRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyHR
    {
        public string HRName { get; set; }
        public string CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string JobTitle { get; set; }
        public string HREmail { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public Nullable<int> FaxNumber { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
