//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_CRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ClassID { get; set; }
        public string PID { get; set; }
        public string FullName { get; set; }
        public string Sponsorship { get; set; }
        public string EmployementStatus { get; set; }
        public string BillingPersonName { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCountry { get; set; }
        public string BillingPostalCode { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
